
const enum Tags {
    a = "a",
    b = "b",
    br = "br",
    code = "code",
    div = "div",
    em = "em",
    footer = "footer",
    form = "form",
    h1 = "h1",
    h2 = "h2",
    h3 = "h3",
    h4 = "h4",
    h5 = "h5",
    h6 = "h6",
    header = "header",
    hr = "hr",
    i = "i",
    iframe = "iframe",
    img = "img",
    input = "input",
    label = "label",
    li = "li",
    mark = "mark",
    ol = "ol",
    option = "option",
    p = "p",
    // script = "script",
    section = "section",
    select = "select",
    small = "small",
    span = "span",
    strong = "strong",
    // style = "style",
    textarea = "textarea",
    sub = "sub",
    sup = "sup",
    svg = "svg",
    u = "u",
    ul = "ul",
    video = "video"
}

export default Tags;
